table: contact_employments

columns:

  - name: contact_id
    type: String
    nullable: false
    description: Unique identifier for contact

  - name: employer_name
    type: Nullable(String)
    description: Employer name

  - name: title
    type: Nullable(String)
    description: Job title

  - name: occupation
    type: Nullable(String)
    description: Normalized occupation value

  - name: start_date
    type: Nullable(Date)
    description: Employment start date

  - name: end_date
    type: Nullable(Date)
    description: Employment end date

  - name: is_current
    type: Bool
    description: Current employment flag

  - name: glynac_organization_id
    type: String
    description: Organization identifier

  - name: processing_date
    type: Date
    description: Ingestion processing date