table: contact_phones

columns:

  - name: contact_id
    type: String
    nullable: false
    description: Unique identifier for contact

  - name: label
    type: String
    nullable: true
    description: Phone label (mobile, office, facility)

  - name: number
    type: String
    nullable: false
    description: Normalized phone number

  - name: glynac_organization_id
    type: String
    nullable: false
    description: Organization identifier

  - name: processing_date
    type: Date
    nullable: false
    description: Data ingestion processing date